Spectronaut params
Proteobench/ProteoBench pull request #437
Opened 2024-11-11 21:34 UTC by wolski

This pull request implements the parsing of spectronaut parameters.

2024-11-12 12:31 UTC, enryH commented on test/params/spectronaut_Experiment1_ExperimentSetupOverview_BGS_Factory_Settings.csv
> +predictors_library,:	False
I think this can be parsed better?

2024-11-12 12:32 UTC, enryH commented on proteobench/io/params/spectronaut.py
> +    params.predictors_library = extract_value(lines, "Hybrid (DDA + DIA) Library")
or you want to only test that the strings `startswith` the collon?

2024-11-12 12:36 UTC, enryH requested changes
some of the parameters need a bit of stripping. and I think for a future iterations we might ask for an easier format - I imagine this can easily lead to a fragile parsing experience when they update their log.

2024-11-12 14:12 UTC, wolski commented
@enryH, they are now parsed better. I sent an email to BGS support and asked for a machine-readable format and if they could report a number instead of "System Default." But for now, it's how it is.
Since you typically start a spectronaut analysis from a GUI, the BGS Factory Settings.txt is the only one we have to parse the parameters from, as far as I can see.

2024-11-12 14:14 UTC, wolski commented on test/params/spectronaut_Experiment1_ExperimentSetupOverview_BGS_Factory_Settings.csv
> +precursor_mass_tolerance,System Default
asked BGS support.

2024-11-13 07:58 UTC, wolski commented
This is what BGS support writes:


In the case of MS1/MS2 Mass Tolerance Strategy, the System Default values can be found by hovering over the setting name. Additionally, this information can be found in the Spectronaut user manual. As you can see, this value depends on the type of mass analyzer used in the experiment.

![image](https://github.com/user-attachments/assets/46cdabc3-5997-4f46-a26f-e42cd057a24d)


I will replace System Default with 40ppm.

2024-11-13 08:29 UTC, merged