Added Proline and Custom formats
Proteobench/ProteoBench pull request #67
Opened 2023-06-14 06:01 UTC by veitveit

The following has been done:
a) Added Proline input. Works at least with the Proline output in WOMBAT. Some issues might arise from naming the quantititave columns 
b) Added a Custome tab-delimited input format
c) Added more help in the web interface explaining the intput formats

2023-06-20 08:46 UTC, enryH commented on proteobench/modules/dda_quant/module.py
> +        quant_raw_df = filtered_df.groupby(["peptidoform", "Raw file"]).Intensity.mean()
Selects the correct numeric column as the previous behaviour of discarding non-numeric columns was depreciated in `pandas=2`

2023-07-08 12:49 UTC, RobbinBouwmeester requested changes
- [ ] Could you remove the /Data/ folder? It is not clear why this is included
- [ ] Could you revert changes in the Test_workflow.ipynb

2023-08-17 16:59 UTC, veitveit commented
Requested changes should be done.

Now this also contains a first documentation in Sphinx (docs folder). I assume we still need to automate generating it in the CI.

Help is appreciated :-)

2023-08-17 17:09 UTC, veitveit commented
Now also with a github actions workflow for building the docs. No idea whether this works though

2023-09-04 08:23 UTC, enryH commented on proteobench/modules/template/plot.py
> -# ? Should we define two function to implement instead of an ABC?
So you have chosen to not use an ABC, but a class after all? The class has no state and the module already groups the two functions. I would just use plain functions here.

2023-09-04 08:26 UTC, enryH commented
The module level documentation is really great! However, the main config for Sphinx (`conf.py`) was updated (I guess overwritten?). Was this intended? I saw Ralf is updating the readthedocs integration, so maybe we should coordinate what theme we want.

2023-09-04 15:33 UTC, veitveit commented
Wasn't the readthedocs moved to https://github.com/Proteobench/proteobench.github.io? Otherwise, yes, I overwrote it.

2023-09-08 10:33 UTC, enryH commented on proteobench/modules/template/plot.py
> -# ? Should we define two function to implement instead of an ABC?
I would just provide empty functions raising `NotImplementedError`s for the template. I'll revert the changes and make a commit.

2023-09-08 10:34 UTC, enryH commented
> Wasn't the readthedocs moved to https://github.com/Proteobench/proteobench.github.io? Otherwise, yes, I overwrote it.

@RalfG I guess it's up to you to decide:)

2023-09-09 13:26 UTC, RobbinBouwmeester approved these changes

2023-09-09 13:27 UTC, merged

2023-09-13 08:56 UTC, RalfG commented
> > Wasn't the readthedocs moved to https://github.com/Proteobench/proteobench.github.io? Otherwise, yes, I overwrote it.
> 
> @RalfG I guess it's up to you to decide:)

The idea back at the Copenhagen hackathon was to have dev-oriented, Sphinx-build Python API documentation on https://proteobench.readthedocs.io, and to have the main user-oriented landing page and documentation on https://proteobench.github.io (potentially forwarded to a custom domain at https://protebench.org?).

For the former I had started Sphinx docs in this repo, which Veit has partially overwritten (but that is totally fine). For the latter, I had started a Quarto-based static website on https://github.com/Proteobench/proteobench.github.io.

2023-09-13 08:58 UTC, RalfG commented
The only thing that is not entirely clear to me, @veitveit, is that you have added a GitHub action to build the docs instead of using the build system on readthedocs.org? I did not see a new build after this PR appear on https://proteobench.readthedocs.io?

2023-09-13 09:18 UTC, veitveit commented
@RalfG I added this one: https://github.com/Proteobench/ProteoBench/blob/main/.github/workflows/build_docs.yml
But did not check whether anything is triggered.

2023-09-14 15:51 UTC, RalfG commented
I saw the workflow, but it seems that `readthedocs/github-action@master` is not an existing action. With #72, docs now automatically build on the readthedocs.org servers.